export const TOTAL_YEARLY = "TOTAL_YEARLY";
export const TOTAL_MONTHLY = "TOTAL_MONTHLY";
export const TOTAL_DAILY = "TOTAL_DAILY";
export const TOTAL_YEARLY_BY_MONTH = "TOTAL_YEARLY_BY_MONTH";
export const DAILY_EMPLOYEE_DATA = "DAILY_EMPLOYEE_DATA";
export const MONTHLY_EMPLOYEE_DATA = "MONTHLY_EMPLOYEE_DATA";
export const MONTHLY_SUBSCRIPTIONS_DATA = "MONTHLY_SUBSCRIPTIONS_DATA";
export const DAILY_SUBSCRIPTIONS_DATA = "DAILY_SUBSCRIPTIONS_DATA";
